// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wphtinxfspycdlbcdgqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwaHRpbnhmc3B5Y2RsYmNkZ3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0ODAzMjAsImV4cCI6MjA4NDA1NjMyMH0.f0sKP6dIAtR__K5eRU3tRt7e2ieZQdbw5hPcSJLuJXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});